Configs: &Default
  Version: 2
  AppName: Столичная
  AgreementSettings:
    Content: Profile.html
  ServerSettings:
    VerifyPhoneCodeLength: 6
    ForceDisableInputSocial: False
    CardValidationEnabled: False
  Analytics:
    Google: 
      Enable: True
  CachePolicyEnabled: True
  ResendCodeConfirmTime: 60 #Время ожидания для повторной отправки кода подтверждения (секунды)
  AnonymVirtualCard: False #Виртуальная карта для анонима 
  ShowOptions:
    ProfileCardViewModel: OnlyAuth #Отображать в меню "Моя карта" All or OnlyAuth
    PersonalOffersViewModel: OnlyAuth #Отображать в меню "Персональные акции" OnlyAuth or Never
    PersonalGoodsViewModel: OnlyAuth #Отображать в меню "Любимые товары" OnlyAuth or Never
  Localization:
    Enable: False #Подключение локализации
    ViewLocalization: False #Отображение стартового экрана с выбором языка при первом запуске приложения

Development:
  <<: *Default
  LoymaxEndpoint: 
    AppUrl: https://mapp.guildmail.ru/publicapi/ 
    ClientId: ""
    PublicKey: ""
    OfferId: "7685e4d8-47f8-4cba-55ce-c93dafcc7974"
    PrivacyId: "f8da26f6-36f9-4ec9-f1a9-e8e1b0a5d709"
  HockeyApp: 
    AppKey:
      Android: ""
      Ios: ""
    EnableCrashManager: False
  PushNotification: 
    Enable: true

Staging:
  <<: *Default
  LoymaxEndpoint: 
    AppUrl: https://mapp.guildmail.ru/publicapi/
    ClientId: ""
    PublicKey: ""
    OfferId: "7685e4d8-47f8-4cba-55ce-c93dafcc7974"
    PrivacyId: "f8da26f6-36f9-4ec9-f1a9-e8e1b0a5d709"
  HockeyApp:
    AppKey:
      Android: ""
      Ios: ""
    EnableCrashManager: True
  PushNotification: 
    Enable: true

Production:
  <<: *Default
  LoymaxEndpoint:
    AppUrl: https://mapp.guildmail.ru/publicapi/
    ClientId: ""
    PublicKey: ""
    OfferId: "7685e4d8-47f8-4cba-55ce-c93dafcc7974"
    PrivacyId: "f8da26f6-36f9-4ec9-f1a9-e8e1b0a5d709"
  HockeyApp: 
    AppKey:
      Android: ""
      Ios: ""
    EnableCrashManager: False
  PushNotification: 
    Enable: True