Order:
  - SignInViewModel.Title
  - ProfileCardViewModelOld.Title
  - OffersViewModel.Title
  - PersonalOffersViewModel.Title
  - PersonalGoods.Title
  - ShoppingBasketsViewModel.Title
  - BaseMerchantsViewModel.Title
  - PurchaseHistoryViewModel.Title
  - NotificationsViewModel.Title
  - ProfileViewModel.Title
  - SupportService.Title 
  - AboutApp.Title
  - ClientSettingsViewModel.Title
  - ClientLogsViewModel.Title